<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PC-Desktop" failures="3" tests="5" name="Test" time="0.032" errors="0" timestamp="2023-05-14T22:01:55 GMT-05:00">
  <testcase classname="smarttech.ny.TestNGChallenges.FailedTestCases" name="getTest1" time="0.005"/>
  <testcase classname="smarttech.ny.TestNGChallenges.FailedTestCases" name="getTest2" time="0.001"/>
  <testcase classname="smarttech.ny.TestNGChallenges.FailedTestCases" name="getTest3" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.ny.TestNGChallenges.FailedTestCases.getTest3(FailedTestCases.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTest3 -->
  <testcase classname="smarttech.ny.TestNGChallenges.FailedTestCases" name="getTest4" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.ny.TestNGChallenges.FailedTestCases.getTest4(FailedTestCases.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTest4 -->
  <testcase classname="smarttech.ny.TestNGChallenges.FailedTestCases" name="getTest5" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.ny.TestNGChallenges.FailedTestCases.getTest5(FailedTestCases.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTest5 -->
</testsuite> <!-- Test -->
